# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('学号', models.CharField(blank=True, max_length=15, null=True)),
                ('姓名', models.CharField(blank=True, max_length=20, null=True)),
                ('性别', models.CharField(max_length=10, null=True)),
                ('学院', models.CharField(max_length=30, null=True)),
                ('身高', models.FloatField(blank=True, null=True)),
                ('体重', models.FloatField(blank=True, null=True)),
                ('肺活量', models.IntegerField(blank=True, null=True)),
                ('跑_50米', models.FloatField(blank=True, null=True)),
                ('立定跳远', models.FloatField(blank=True, null=True)),
                ('坐位体前屈', models.FloatField(blank=True, null=True)),
                ('跑_800米', models.FloatField(blank=True, null=True)),
                ('跑_1000米', models.FloatField(blank=True, null=True)),
                ('仰卧起坐', models.IntegerField(blank=True, null=True)),
                ('引体向上', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
