# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180227_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='可选项，若为空格则摘取正文前25个字符', max_length=25, null=True, verbose_name='摘要'),
        ),
    ]
